pom.xml
test/org/stringtemplate/v4/test/BaseTest.java
test/org/stringtemplate/v4/test/TestCompiler.java
test/org/stringtemplate/v4/test/TestRenderers.java

This pull request addresses the trailing separator issue described in #103. In addition, it makes the following changes to the test output folder:
1. It generates a unique `tmpdir` folder for each test.
2. When running the tests using Maven, it places the temporary folder within the `target` folder, which means the temporary directories are removed when you run `mvn clean`.
This pull request supersedes #104 and #91.

Unique test folders

---

contributors.txt
src/org/stringtemplate/v4/STGroup.java
test/org/stringtemplate/v4/test/TestDictionaries.java

I believe this is one way to fix the issue 114. When a <% %> template was used as a dictionary value the %'s were not being stripped. 
I tested the change with this group template
```
delimiters "$","$"
d1 ::= [
"p": <%hi%>
]
main() ::= <<$d1.p$>>
```
and the problem was fixed (expected result `hi` was returned).
Fixes #114

fix issue 114

---

doc/null-vs-empty.md

Vertical bars used in inline code blocks still need to be escaped with a backslash, otherwise the table formatting will break.

Fix table in null-vs-empty.md

---

doc/cheatsheet.md

The second half of this table was being displayed as a paragraph.

Doc - Fix formatting of functions table

---

doc/expr-options.md
doc/templates.md

Whether accidental or intended to force formatting, these tags are unnecessary, and in places, they grin through to the surface. I've found a way to make it look right in markdown.

Remove  HTML tags from expr-options.md and templates.md

---

contributors.txt
doc/groups.md
doc/index.md
doc/introduction.md

As I read the introductory documentation I noticed a few typos and the odd place where the meaning was obscure to a beginner. I guess these parts don't get much attention from those who've already mastered StringTemplate so I thought I'd pitch in while I'm uniquely qualified.
Other changes are back-tick quoting in-line code in what seems to be the house style (but also helps readability).
The worst garble I found is already covered by #134, so I haven't duplicated that fix.

Fix typos in introductory documentation

---

src/org/stringtemplate/v4/compiler/CodeGenerator.g
test/org/stringtemplate/v4/test/TestGroupSyntax.java

- Make sure errors in **CodeGenerator.g** get reported to listeners
- Fix handling of indented comment at end of template
Fixes #138

Fix handling of indented comment at end of template

---

contributors.txt
doc/templates.md

Markdown table in documentation did not render properly. Now it does.

Fixed typo in doc/templates.md.

---

doc/inheritance.md

Missing argument in Java1_4.stg example:
context [/class /constants /_sub1] 1:13 passed 2 arg(s) to template /constant with 1 declared arg(s)
at org.stringtemplate.bazel.STRules.process(STRules.java:289)
at org.stringtemplate.bazel.STRules.main(STRules.java:68)

Fix inheritance example

---

src/org/stringtemplate/v4/compiler/Compiler.java
test/org/stringtemplate/v4/test/BaseTest.java

Right now, the way subtemplateCount is implemented is not thread safe
since the ++ operator in java does not atomically read and write the
incremented integer value. Even if each thread gets it's own STGroup, etc. we can get race conditions since the subtemplateCount field is static. This can lead to a template redefinition since a given thread may read the same for the integer twice, causing two subtemplates to have the same generated name if another thread reads the value before and writes the stale value afterwards.
I tracked this down while debugging an issue which spit out the error message like:
``` 
common.stg 8:125: redefinition of template SUBTEMPLATE
``` 
There are similar reports in https://github.com/antlr/stringtemplate4/issues/61

Use an AtomicInteger for subtemplateCount to avoid race condition

---

contributors.txt
src/org/stringtemplate/v4/DateRenderer.java
src/org/stringtemplate/v4/Interpreter.java
src/org/stringtemplate/v4/compiler/Compiler.java

[Double-brace initialization](https://stackoverflow.com/questions/1958636/what-is-double-brace-initialization-in-java) is commonly abused for its brevity, but has [performance](https://stackoverflow.com/questions/924285/efficiency-of-java-double-brace-initialization) and clarity implications.
The use of `Collections.unmodifiableSet` and `unmodifiableMap` prevents outsider classes from modifying these collections, which is not desirable.

Remove double-brace initialization and wrap constant collections in Collection.unmodifiable{Set,Map}

---

src/org/stringtemplate/v4/Interpreter.java
src/org/stringtemplate/v4/STGroup.java

This amends #233 with a minor change to the signature of `STGroup#getAttributeRenderer`, as [requested](https://github.com/antlr/stringtemplate4/pull/235#discussion_r362019387) by @sharwell.

Fix signature of STGroup.getAttributeRenderer

---

doc/adaptors.md
src/org/stringtemplate/v4/ModelAdaptor.java
src/org/stringtemplate/v4/STGroup.java
src/org/stringtemplate/v4/misc/AggregateModelAdaptor.java
src/org/stringtemplate/v4/misc/MapModelAdaptor.java
src/org/stringtemplate/v4/misc/ObjectModelAdaptor.java
src/org/stringtemplate/v4/misc/STModelAdaptor.java
test/org/stringtemplate/v4/test/TestModelAdaptors.java

As suggested in #233
The only change introduced by this that can be considered breaking is the removal of the superclass `MapModelAdaptor` from `AggregateModelAdaptor`. The inheritance was replaced by composition. This had to be done because `MapModelAdaptor` is now a `ModelAdaptor<Map>`, while `AggregateModelAdaptor` needs to be a `ModelAdaptor<Aggregate>`. Previously, `AggregateModelAdaptor` could not handle a Map, so I think this "breaking" change should not cause any issues.

Generify ModelAdaptor

---

src/org/stringtemplate/v4/NumberRenderer.java
src/org/stringtemplate/v4/StringRenderer.java

Reverts NumberRenderer and StringRenderer to accept Object instead of Number or String respectively.
NumberRenderer always worked with Object before.
Actually it should be called FormatRenderer or similar because it merely uses Formatter, nothing Number-specific.
StringRenderer now uses the pre-#233 behaviour of accepting Object at runtime, but failing if the actual value is not a String due to the forced cast.
The main motivation is that #233 broke code like this:
```java
class CustomStringRenderer extends StringRenderer {
@Override
public String toString(Object value, String formatString, Locale locale) {
if ("decap".equals(formatString)) { return ... };
return super.toString(value, formatString, locale);
}
}
```
Now suddenly that method no longer overrides `toString` from …

Fix backward compatibility issues introduced by #233

---

pom.xml
revapi.json

Re-enables the Revapi Maven plugin.
I tried to fix the problem that it breaks when releasing a new version by explicitly setting the `oldVersion` it should compare against.
~I believe all that needs to be done next time is update this to the version number of the newly released version. E.g., *after* releasing v4.4, change `<oldVersion>4.3</oldVersion>` to `<oldVersion>4.4</oldVersion>` in a new commit. The important part is the new version needs to be available on Maven by the time this commit is made.~
Update: don't have to do anything any more.

Re-enable Revapi

---

src/org/stringtemplate/v4/misc/ObjectModelAdaptor.java

This addresses #249, and is consistent with `getProperty` in that it converts any Exception to a `STNoSuchPropertyException`.
Closes #249

Ignore all Exceptions during method and field lookup in ObjectModelAdaptor

---

contributors.txt
doc/faq/index.md
doc/faq/object-models.md
doc/scala-model-adaptor.md

The existing scala adaptor documentation is written in a Java-like way and not the way typical Scala would be written. Additionally, the ST calls it uses have been refactored/deprecated. This PR updates the documentation.
We would also like to change the filename (and references to this file) from `object-models.md` to something more descriptive like `scala-model-adaptor.md`. We'll make the appropriate commits if we get the OK.
Co-authored-by: James Mahler <jmahler@andrew.cmu.edu>
Co-authored-by: Yang LI <zjzsliyang@gmail.com>
Co-authored-by: dyuan0226 <dyuan1@andrew.cmu.edu>

Updating scala documentation to be more idiomatic and work with ST4

---

src/org/stringtemplate/v4/StringRenderer.java
test/org/stringtemplate/v4/test/TestRenderers.java

Changed the `StringRenderer.encodeHTML` method, i.e. the implementation for `format="xml-encode"`, in order to support Unicode characters encoded as two `char`s (surrogate pairs). An example where this problem occurred was with emojis, as outlined in #260. While the old implementation produced two invalid HTML entities `&#55358;&#56947;` for the two characters encoding the emoji "🩳", after this change it only generates one entity, namely `&#129651;` (ref.: https://unicode-table.com/de/1FA73/)
Closes #260

Correctly handle surrogate pairs in StringRenderer.encodeHTML

---

contributors.txt
src/org/stringtemplate/v4/misc/Misc.java
test/org/stringtemplate/v4/test/TestGroups.java

This reintroduces closing angle bracket escaping as discussed in https://github.com/antlr/stringtemplate4/issues/198 .
Note that this applies only to `STGroup`, not `ST` -- same way it was in 4.0.4 and prior.

Fix escaping for closing angle brackets.

---

contributors.txt
src/org/stringtemplate/v4/STGroup.java

Fix for NPE in `STGroup::getUrl` when `Thread.currentThread().getContextClassLoader()` is null.  We experienced this issue with version 4.0.8 in an OSGI environment where `Thread.currentThread().getContextClassLoader()` was null but `this.getClass().getClassLoader()` was populated and would have been able to resolve the `fileName` if a NPE had not been thrown.  Added null check for both classloaders.  I tried to follow your existing code formatting, please let me know if any changes are needed! 🤓 
Stacktrace: 
```
can't load group file jar:file:/usr/local/tomcat/webapps/ROOT/WEB-INF/lib/killbill-invoice-0.22.10.jar!/org/killbill/billing/invoice/dao/InvoiceSqlDao.sql.stg
Caused by: java.lang.NullPointerException
at org.stringtemplate.v4.STGroup.getURL(STGroup.java:774)
at …
```

Fix for NPE when Thread.currentThread().getContextClassLoader() is null.

---

.gitignore
BUILD.bazel
WORKSPACE.bazel
src/BUILD.bazel
src/org/stringtemplate/v4/STGroupDir.java
src/org/stringtemplate/v4/misc/STMessage.java
test/BUILD.bazel

Perform some prerequisite work for Bazel support in StringTemplate 4.
I need to do the same to ANTLRv3 before I can come back and update the `TODO` in `WORKSPACE.bazel` with an appropriate commit.

Bazel support

---

pom.xml

- Fixes #300
This needs no manual installation of test.jar to local repository.
Local results:
```
[WARNING] Tests run: 645, Failures: 0, Errors: 0, Skipped: 2
```
```
Test set: org.stringtemplate.v4.test.TestGroupsFromCLASSPATH
-------------------------------------------------------------------------------
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.011 s - in org.stringtemplate.v4.test.TestGroupsFromCLASSPATH
```
and its dependencies transit to client:
```
[INFO] |  \- org.seleniumhq.selenium:selenium-json:jar:4.1.3:compile
[INFO] +- org.antlr:ST4:jar:4.3.3-SNAPSHOT:compile
[INFO] |  \- org.antlr:antlr-runtime:jar:3.5.2:compile
[INFO] +- org.eclipse.jetty:jetty-server:jar:11.0.9:compile
```

Configure surefire to include test.jar in tests

---

README.md
doc/groups.md
doc/introduction.md
doc/java.md
doc/motivation.md
doc/regions.md
doc/releasing-st4.md
doc/renderers.md
doc/templates.md
pom.xml
src/org/stringtemplate/v4/compiler/CodeGenerator.g
src/org/stringtemplate/v4/misc/Misc.java
test/org/stringtemplate/v4/test/BaseTest.java
test/org/stringtemplate/v4/test/TestEarlyEvaluation.java
test/org/stringtemplate/v4/test/TestGroupsFromCLASSPATH.java

This PR fixes various typos found in the documentation and source files.
It also changes with various links from `http` to `https`.

Fixing typos
